### ISSUE TITLE
Comments on the Test ADE draft for CityGML 3.0

### ISSUE THREAD

**Issue by TatjanaKutzner** [3dcitydb/extension-test-ade#4]
Hi Zhihang,
I checked your draft and have a few comments:

Code lists:
- In the CityGML 3.0 Conceptual Model, names of code lists for the attributes `class`, `function`, and `usage` always contain the full name of the class to which the attributes belong.
Otherwise problems will occur when the UML model contains several classes that have the same attributes.
This should also be a best practice for ADEs.
Thus, I suggest to rename `ClassValue`, `FunctionValue`, and `UsageValue` into `BuildingUndergroundClassValue`, `BuildingUndergroundFunctionValue`, and `BuildingUndergroundUsageValue`.

Classes `DHWFacilities` and `LightingFacilities`:
- The attribute `totalValue` is not required, it is already inherited from the class `Facilities`.

Classes `Facilities`, `DHWFacilities`, `LightingFacilities`:
- Usually class names of feature types are in singular, not plural. Thus I suggest to rename these classes into `Facility`, `DHWFAcility`, and `LightingFacility`.

Data type `EnergyPerformanceCertification`: 
- The attribute names `certificationname` and `certificationid` should be changed to `certificationName` and `certificationId` or `certificationID`.

Class `AbstractBuildingUnderground`:
- The class should also inherit from one of the Space classes in the CityGML 3.0 Core module. Probably from `AbstractOccupiedSpace`.
- There is a typo in the association name `adress`. This should be `address`.
- The association to `BuildingProperties` is missing an arrow, so the direction of the association is not clear.

Colours:
- The colouring should be explained. Also I suggest that the meaning the colours already in use in the CityGML conceptual model should not be changed. Thus, the classes coming from the CityGML modules should be in blue.

**Comment by yaozhihang** [comment]
@TatjanaKutzner thanks very much for the review. I'll do the update asap.

**Comment by clausnagel** [comment]
I agree with all of Tatjana's comments.

With spaces and space boundaries, CityGML 3.0 introduces a new core concept that must also be used in ADEs. See [Requirement 49 in chapter 9.5.2 of the CityGML 3.0 specification](https://docs.ogc.org/is/20-010/20-010.html#toc71):

> Features representing spaces or space boundaries SHALL be derived either directly or indirectly from core:AbstractSpace or core:AbstractSpaceBoundary respectively.

At least from the name `AbstractBuildingUnderground` I guess that this feature class represents a space and therefore _must_ be derived from one of the space classes in CityGML 3.0 (I also think it should probably be `AbstractOccupiedSpace`). By doing so, it will automatically inherit spatial representations. Thus, it must also be checked whether the spatial representations in the current UML are really required or should better be removed.

**Comment by yaozhihang** [comment]
Fixed with 8ff17da13443c7479e5f915e0a5984baed8f48bf. I also removed the spatial representations from the earlier UML and introduced a geometry property `genericGeometry` in addition. It shows the possibility that an ADE class can not only inherit spatial representations from the CityGML Core module, but also has its own one.
