### ISSUE TITLE
Only high level nodes are shown/imported

### ISSUE THREAD

**Issue by e3DChristoph** [3dcitydb/extension-test-ade#6]
Hey,

I don't know if this might be a wanted feature, but when I import an ADE only the highest level Nodes are shown in the Feature Type List. Why are the child nodes not there if I e.g. just want to select a subgroup of an Feature and not the full one?

Maybe this should be an Issue for the Importer/Exporter and not the ADE Extension. If so please let me know so I can move it.

Thanks

**Comment by clausnagel** [comment]
See answer in #5.
